# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  -group: default
  registryLogin: 'bkucheriavyi'
  registryPassword: $(dockerPassword)
  registryUrl: 'bkucheriavyi.azurecr.io'
  
  imageName: '$(registryUrl)/lissajou-curves-react:$(build.buildId)'

steps:
#- script: docker build -f ./Dockerfile -t $(imageName) .
#  displayName: 'Build image'
- script: |
      docker login -u $(registryLogin) -p $(registryPassword) $(registryUrl)
      docker push $(imageName)
  displayName: 'Log in and push image into container registry'
